//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NClap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NClap.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for the &apos;{1}&apos; command line option..
        /// </summary>
        internal static string BadArgumentValue {
            get {
                return ResourceManager.GetString("BadArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for the &apos;{1}&apos; command line option.
        ///Reason:
        ///    {2}.
        /// </summary>
        internal static string BadArgumentValueWithReason {
            get {
                return ResourceManager.GetString("BadArgumentValueWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; validation attribute may not be applied to a field or property of type &apos;{1}&apos;..
        /// </summary>
        internal static string BadValidationAttribute {
            get {
                return ResourceManager.GetString("BadValidationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open command line argument file &apos;{0}&apos; : &apos;{1}&apos;..
        /// </summary>
        internal static string CannotReadArgumentAnswerFile {
            get {
                return ResourceManager.GetString("CannotReadArgumentAnswerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value of &apos;{0}&apos; for argument &apos;{1}&apos; conflicts with the use of argument &apos;{2}&apos;.  These arguments may not both be specified..
        /// </summary>
        internal static string ConflictingArgument {
            get {
                return ResourceManager.GetString("ConflictingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find argument member &apos;{0}&apos; referenced by the &apos;ConflictsWith&apos; attribute attached to member &apos;{1}&apos;..
        /// </summary>
        internal static string ConflictingMemberNotFound {
            get {
                return ResourceManager.GetString("ConflictingMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the constituent types of &apos;{0}&apos; are not supported as argument types..
        /// </summary>
        internal static string ConstituentTypeNotSupported {
            get {
                return ResourceManager.GetString("ConstituentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string DefaultPrompt {
            get {
                return ResourceManager.GetString("DefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value for member &apos;{0}&apos; is of type &apos;{1}&apos; but must be of type &apos;{2}&apos;..
        /// </summary>
        internal static string DefaultValueIsOfWrongType {
            get {
                return ResourceManager.GetString("DefaultValueIsOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not exist..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateArgument {
            get {
                return ResourceManager.GetString("DuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate argument long name specification: {0}..
        /// </summary>
        internal static string DuplicateArgumentLongName {
            get {
                return ResourceManager.GetString("DuplicateArgumentLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate argument short name specification: {0}..
        /// </summary>
        internal static string DuplicateArgumentShortName {
            get {
                return ResourceManager.GetString("DuplicateArgumentShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple default arguments with the same position index were seen..
        /// </summary>
        internal static string DuplicatePositionArguments {
            get {
                return ResourceManager.GetString("DuplicatePositionArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element type of &apos;{0}&apos; is not supported as an argument type..
        /// </summary>
        internal static string ElementTypeNotSupported {
            get {
                return ResourceManager.GetString("ElementTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The long name specified for an enum type&apos;s value is invalid or already in use..
        /// </summary>
        internal static string EnumValueLongNameIsInvalid {
            get {
                return ResourceManager.GetString("EnumValueLongNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short name specified for an enum type&apos;s value is invalid or already in use..
        /// </summary>
        internal static string EnumValueShortNameIsInvalid {
            get {
                return ResourceManager.GetString("EnumValueShortNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input:
        ///{0}.
        /// </summary>
        internal static string ExceptionWasThrownParsingInputLine {
            get {
                return ResourceManager.GetString("ExceptionWasThrownParsingInputLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The implementing type for this verb (&apos;{0}&apos;) does not implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string ImplementingTypeNotIVerb {
            get {
                return ResourceManager.GetString("ImplementingTypeNotIVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid argument long name was found..
        /// </summary>
        internal static string InvalidArgumentLongName {
            get {
                return ResourceManager.GetString("InvalidArgumentLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid usage..
        /// </summary>
        internal static string InvalidUsage {
            get {
                return ResourceManager.GetString("InvalidUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; in type &apos;{1}&apos; cannot be associated with an argument..
        /// </summary>
        internal static string MemberNotSupported {
            get {
                return ResourceManager.GetString("MemberNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required named argument &apos;/{0}&apos;..
        /// </summary>
        internal static string MissingRequiredNamedArgument {
            get {
                return ResourceManager.GetString("MissingRequiredNamedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required positional argument &apos;&lt;{0}&gt;&apos;..
        /// </summary>
        internal static string MissingRequiredPositionalArgument {
            get {
                return ResourceManager.GetString("MissingRequiredPositionalArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not implement an accessible parameterless constructor..
        /// </summary>
        internal static string NoAccessibleParameterlessConstructor {
            get {
                return ResourceManager.GetString("NoAccessibleParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help information available..
        /// </summary>
        internal static string NoHelpAvailable {
            get {
                return ResourceManager.GetString("NoHelpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The positional arguments are not consecutively indexed..
        /// </summary>
        internal static string NonConsecutivePositionalParameters {
            get {
                return ResourceManager.GetString("NonConsecutivePositionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path does exist as a file or directory..
        /// </summary>
        internal static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path exists..
        /// </summary>
        internal static string PathExists {
            get {
                return ResourceManager.GetString("PathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value does not match the regular expression &apos;{0}&apos;..
        /// </summary>
        internal static string StringDoesNotMatchRegEx {
            get {
                return ResourceManager.GetString("StringDoesNotMatchRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is empty..
        /// </summary>
        internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value matches the regular expression &apos;{0}&apos;..
        /// </summary>
        internal static string StringMatchesRegEx {
            get {
                return ResourceManager.GetString("StringMatchesRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating quotes not followed by white space or end of string..
        /// </summary>
        internal static string TerminatingQuotesNotEndOfToken {
            get {
                return ResourceManager.GetString("TerminatingQuotesNotEndOfToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too few elements in the tuple string..
        /// </summary>
        internal static string TooFewElementsInTupleString {
            get {
                return ResourceManager.GetString("TooFewElementsInTupleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not supported for arguments..
        /// </summary>
        internal static string TypeNotSupported {
            get {
                return ResourceManager.GetString("TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique is only applicable to collection arguments..
        /// </summary>
        internal static string UniqueUsedOnNonCollectionArgument {
            get {
                return ResourceManager.GetString("UniqueUsedOnNonCollectionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or parse argument answer file &apos;{0}&apos;..
        /// </summary>
        internal static string UnreadableFile {
            get {
                return ResourceManager.GetString("UnreadableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command line argument &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedArgument {
            get {
                return ResourceManager.GetString("UnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a recognized verb..
        /// </summary>
        internal static string UnrecognizedVerb {
            get {
                return ResourceManager.GetString("UnrecognizedVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated quotes found..
        /// </summary>
        internal static string UnterminatedQuotes {
            get {
                return ResourceManager.GetString("UnterminatedQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string UsageInfoDescriptionHeader {
            get {
                return ResourceManager.GetString("UsageInfoDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXAMPLES.
        /// </summary>
        internal static string UsageInfoExamplesHeader {
            get {
                return ResourceManager.GetString("UsageInfoExamplesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, type: &quot;{0}&quot;.
        /// </summary>
        internal static string UsageInfoHelpAdvertisement {
            get {
                return ResourceManager.GetString("UsageInfoHelpAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string UsageInfoNameHeader {
            get {
                return ResourceManager.GetString("UsageInfoNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONAL PARAMETERS.
        /// </summary>
        internal static string UsageInfoOptionalParametersHeader {
            get {
                return ResourceManager.GetString("UsageInfoOptionalParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMARKS.
        /// </summary>
        internal static string UsageInfoRemarksHeader {
            get {
                return ResourceManager.GetString("UsageInfoRemarksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIRED PARAMETERS.
        /// </summary>
        internal static string UsageInfoRequiredParametersHeader {
            get {
                return ResourceManager.GetString("UsageInfoRequiredParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNTAX.
        /// </summary>
        internal static string UsageInfoSyntaxHeader {
            get {
                return ResourceManager.GetString("UsageInfoSyntaxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid verbs:
        ///{0}.
        /// </summary>
        internal static string ValidVerbsHeader {
            get {
                return ResourceManager.GetString("ValidVerbsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than &apos;{0}&apos;..
        /// </summary>
        internal static string ValueIsNotGreaterThan {
            get {
                return ResourceManager.GetString("ValueIsNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than or equal to &apos;{0}&apos;..
        /// </summary>
        internal static string ValueIsNotGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueIsNotGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not less than &apos;{0}&apos;..
        /// </summary>
        internal static string ValueIsNotLessThan {
            get {
                return ResourceManager.GetString("ValueIsNotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not less than or equal to &apos;{0}&apos;..
        /// </summary>
        internal static string ValueIsNotLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueIsNotLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value not be equal to &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMayNotBe {
            get {
                return ResourceManager.GetString("ValueMayNotBe", resourceCulture);
            }
        }
    }
}
