name: "Build"

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build-linux:
    name: "Build: Linux"
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET Core 6.0 SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore packages
      run: dotnet restore src/NClap.sln

    - name: "Build: Linux (release)"
      run: dotnet build src/NClap.sln --no-restore -c Release

    - name: "Test: .NET 6.0"
      run: dotnet test src/NClap.sln --no-build --no-restore -c Release --verbosity normal -f net60

  build-windows:
    name: "Build: Windows"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core 6.0 SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore packages
      run: dotnet restore src/NClap.sln

    - name: "Build: Windows (release)"
      run: dotnet build src/NClap.sln --no-restore -c Release

    - name: "Test: .NET 4.6.1"
      run: dotnet test src/NClap.sln --no-build --no-restore -c Release --verbosity normal -f net461

    - name: "Test: .NET 6.0"
      run: dotnet test src/NClap.sln --no-build --no-restore -c Release --verbosity normal -f net60
